import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { Row, Col, Button, Nav } from "react-bootstrap";
import Sidebar from "../components/sidebars";

export default function Home({ data }) {
  let active = data.page;
  let items = [];
  for (let i = 1; i <= data.total_pages; i++) {
    items.push(
      <a
        href="#"
        className="text-decoration-none d-flex align-items-center justify-content-center mx-1 rounded-circle"
        style={{ color: active === i ? "#FFF" : "#666666", backgroundColor: active === i ? "#7DB7B4" : "", fontSize: "11px", height: "21px", width: "21px" }}
        onClick={(e) => {
          e.preventDefault();
          Router.push(`/?page=${i}`);
        }}
      >
        {i}
      </a>
    );
  }

  return (
    <div className="p-5 m-0">
      <Head>
        <title>Technical Test from Delegate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="row">
          <div className="col-2 py-5 px-4" style={{ borderRadius: "40px", boxShadow: "10px 10px 24px rgba(166, 180, 200, 0.15)" }}>
            <Sidebar />
          </div>

          <div className="col-10">
            <div className="container">
              <div className="row mb-3">
                <div className="col-1">
                  <Image src="/pencil.svg" height="50" width="50" />
                </div>
                <div className="col-11">
                  <span className="fw-bolder p-0" style={{ fontSize: "11px", color: "#666666" }}>
                    PERFORMANCE
                  </span>
                  <h3 style={{ color: "#666666" }}>Interested Users</h3>
                </div>
              </div>
              <div className="d-flex justify-content-end mb-3">
                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                  }}
                >
                  <div className="input-group input-group-sm" style={{ width: "305px" }}>
                    <span className="input-group-text border-0" id="inputGroup-sizing-sm" style={{ backgroundColor: "rgba(102, 102, 102, 0.04)", borderRadius: "20px 0 0 20px" }}>
                      <Image src="/search.svg" height="13" width="13" />
                    </span>
                    <input type="text" className="form-control shadow-none border-0" placeholder="Search by email or name" style={{ backgroundColor: "rgba(102, 102, 102, 0.04)", borderRadius: "0 20px 20px 0" }} />
                  </div>
                </form>
              </div>
              <div className="d-flex flex-column">
                <h5 className="px-3 mb-3" style={{ color: "#666666" }}>
                  INTERESTED USERS
                </h5>
                <div className="row px-3 mb-3 fw-bolder" style={{ color: "#7983A5" }}>
                  <div className="col-2">ID</div>
                  <div className="col-5">EMAIL</div>
                  <div className="col-5">NAME</div>
                </div>
                {data.data.map((user) => {
                  return (
                    <div className="row p-3 fw-bolder mb-2" style={{ color: "#666666", boxSizing: "border-box", border: "1px solid rgba(102, 102, 102, 0.1)", boxShadow: "10px -6px 17px rgba(166, 180, 200, 0.15)", borderRadius: "12px" }}>
                      <div className="col-2">{user.id}</div>
                      <div className="col-5">{user.email}</div>
                      <div className="col-5">
                        {user.first_name} {user.last_name}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <footer className="d-flex align-items-center justify-content-center">
              <Button
                variant="link"
                className="shadow-none mt-1"
                onClick={(e) => {
                  e.preventDefault();
                  Router.push(`/?page=${active - 1}`);
                }}
                disabled={active == 1}
              >
                <Image src="/arrow_back.png" width="21px" height="16px" />
              </Button>
              {items}
              <Button
                variant="link"
                className="shadow-none mt-1"
                onClick={(e) => {
                  e.preventDefault();
                  Router.push(`/?page=${active + 1}`);
                }}
                disabled={active == data.total_pages}
              >
                <Image src="/arrow_next.svg" width="21px" height="16px" />
              </Button>
            </footer>
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps({ query: { page = 1 } }) {
  const res = await fetch(`https://reqres.in/api/users?page=${page}}`);
  const data = await res.json();

  return { props: { data } };
}
